### MAIN Kometa CONFIGURATION FILE
# Origin URL: https://github.com/Liviu-Curt/my-kometa-config
# python kometa.py -r
#
#########################################################################################

libraries:
  ## MOVIES ##
  MoviesTest:
    collection_files:
      # - file: config/config_1_movies/1.1-Movies_General.yml
      # - file: config/config_1_movies/1.2-Movies_Awards.yml
      # - file: config/config_1_movies/1.3-Movies_Franchises.yml
      # - file: config/config_1_movies/1.4-Movies_Genres.yml
      # - file: config/config_1_movies/1.5-Movies_Holidays
      # - file: config/config_1_movies/1.6-Movies_People.yml
      # - file: config/config_1_movies/1.7-Movies_Specials.yml
      # - file: config/config_1_movies/1.8-Movies_Studios.yml
      # - file: config/config_1_movies/1.9-Movies_Years.yml
      # - file: config/config_1_movies/1.10-Movies_Separators.yml
    operations:
      mass_audience_rating_update: imdb
      delete_collections:
        configured: false
        managed: true
    # remove_overlays: false           # Set this to true to remove all overlays
    overlay_files:
      # - file: config/config_1_movies/overlays/1.1-Movies_Overlays_4K.yml
      # - file: config/config_1_movies/overlays/1.2-Movies_Overlays_Rating.yml
      # - file: config/config_1_movies/overlays/1.3-Movies_Overlays_Audio.yml
      # - file: config/config_1_movies/overlays/1.4-Movies_Overlays_Top.yml

  ## TV SHOWS ##
  # TV Shows:
  #   collection_files:
  #     - file: config/config_2_tv-shows/2.1-TV-Shows_General.yml
  #     - file: config/config_2_tv-shows/2.2-TV-Shows_Awards.yml
  #     - file: config/config_2_tv-shows/2.3-TV-Shows_Franchises.yml
  #     - file: config/config_2_tv-shows/2.4-TV-Shows_Genres.yml
  #     - file: config/config_2_tv-shows/2.5-TV-Shows_Networks.yml
  #     - file: config/config_2_tv-shows/2.6-TV-Shows_Specials.yml
  #     - file: config/config_2_tv-shows/2.7-TV-Shows_Years.yml
  #     - file: config/config_2_tv-shows/2.8-TV-Shows_Separators.yml
  #   operations:
  #     mass_audience_rating_update: imdb
  #   overlay_files:
  #     - file: config/config_2_tv-shows/overlays/2.1-TV-Shows_Overlays_4K.yml
  #     - file: config/config_2_tv-shows/overlays/2.2-TV-Shows_Overlays_Rating.yml
  #     - file: config/config_2_tv-shows/overlays/2.3-TV-Shows_Overlays_Audio.yml
  #     - file: config/config_2_tv-shows/overlays/2.4-TV-Shows_Overlays_Top.yml
  #     - file: config/config_2_tv-shows/overlays/2.5-TV-Shows_Overlays_Canceled.yml


# SETTINGS
#########################################################################################
settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: true
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  overlay_artwork_filetype: jpg
  overlay_artwork_quality: 75

# WEBHOOKS - Send notifications to Discord Hydra server
#########################################################################################
webhooks:
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:

# REQUIRED CONNECTIONS
#########################################################################################
plex:
  url: http://192.168.150.0:32400/
  token:
  timeout: 60
  db_cache:
  clean_bundles: false
  empty_trash: false
  optimize: false
  verify_ssl:
tmdb:
  apikey: 
  language: en
  cache_expiration: 60
  region:

# OPTIONAL CONNECTIONS
# Can be individually specified per library as well
#########################################################################################
# TAUTULLI - Monitor Plex server activity and track variour statistics
tautulli:
  url: 
  apikey: 
# GITHUB - Added to avoid rate limits when requesting data
github:
  token: 
# OMDb - Open Movi Database for fetching movie information and posters  
omdb:
  apikey: 
  cache_expiration: 60
# MDBList - Dynamic lists from Trakt.tv using multiple ratings and keywords
mdblist:
  apikey: 
  cache_expiration: 60
# AniDB - Anime and Manga List
anidb:
  username: 
  password: 
  language: en
  client:

# TRAKT - Discover what's hot and where you can watch it  
trakt:
  client_id: 
  client_secret: 
  pin: 
  authorization:
    # everything below is autofilled by the script
    access_token: 
    token_type: Bearer
    expires_in: 
    refresh_token: 
    scope: public
# MAL - My Anime List
mal:
  client_id: ####################
  client_secret: ####################
  authorization:
    # everything below is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:

# NOTIFICATION CONNECTIONS
#########################################################################################
# NOTIFIARR - Manage notifications via Discord
notifiarr:
  apikey: ####################################
# GOTIFY - Simple server for sending and receiving messages
gotify:
  url: http://192.168.1.12:80
  token: ####################################

# RADARR - See all your upcoming MOVIES in one convenient location 
# radarr:
#   url: http://192.168.1.12:7878
#   token: ################################
#   add_missing: false
#   add_existing: false
#   upgrade_existing: false
#   monitor_existing: false
#   root_folder_path: S:/Movies
#   monitor: true
#   availability: announced
#   quality_profile: HD-1080p
#   tag:
#   search: false
#   radarr_path:
#   plex_path:
#   ignore_cache: false
# SONARR - See all your upcoming TV SHOWS in one convenient location   
# sonarr:
#   url: http://192.168.1.12:8989
#   token: ################################
#   add_missing: false
#   add_existing: false
#   upgrade_existing: false
#   monitor_existing: false
#   root_folder_path: S:/TV Shows
#   monitor: all
#   quality_profile: HD-1080p
#   language_profile: English
#   series_type: standard
#   season_folder: true
#   tag:
#   search: false
#   cutoff_search: false
#   sonarr_path:
#   plex_path:
#   ignore_cache: false